<form method="POST" class="flex flex_direction--column flex_justify_content--center" style="box-sizing: border-box;">
    <div class="flex flex_direction--column flex_align_items--center">
        <h5>
            Are you sure about this operation? Account will be deleted permanently and
            you won't be able to recover it.
        </h5>
        <h5>
            Think twice, dude
        </h5>

        <div class="flex flex_direction--row gap--16px">
            <a href="/account">
                <input type="button" value="Go back">
            </a>
            
            <input type="submit" value="Delete">
        </div>
    </div>
</form>