<form method="POST" class="flex flex_direction--column flex_justify_content--center" style="box-sizing: border-box;">
    <div class="flex flex_direction--column flex_align_items--center">
        <div class="flex flex_direction--row flex_justify_content--center gap--16px">
            <div class="flex flex_direction--column">
                <input name="name" type="text" required maxlength="24" placeholder="Name" value="<?= $values->name; ?>">
                <input name="surname" type="text" required maxlength="24" placeholder="Surname"value="<?= $values->surname; ?>">
                <input name="middlename" type="text" maxlength="24" placeholder="Middlename" value="<?= $values->middlename; ?>">
                <input name="username" type="text" required maxlength="16" placeholder="Username" value="<?= $values->username; ?>">

                <select name="gender_id" required value="<?= $values->gender_id; ?>">
                    <option value="" disabled selected hidden>Gender</option>
                    <option value="1">Male</option>
                    <option value="2">Female</option>
                </select>
            </div>
            <div class="flex flex_direction--column">
                <input name="email" type="email" required maxlength="320" placeholder="E-mail" value="<?= $values->email; ?>">
                <input name="phoneNumber" type="tel" placeholder="Phone number" value="<?= $values->phoneNumber; ?>">

                <input name="birthDate" type="text" onfocus="(this.type='date')" onblur="(this.type='text')" placeholder="Birth date"
                        value="<?= $values->birthDate; ?>">

                <input name="password" type="password" maxlength="32" minlength="8" placeholder="Password">
                <input name="repeat-password" type="password" maxlength="32" minlength="8"  placeholder="Repeat password">
            </div>
            <div class="flex flex_direction--column">
                <input name="image" type="file" accept="image/jpeg, image/png">
            </div>
        </div>

        <div class="flex flex_direction--row gap--16px">
            <a href="/account">
                <input type="button" value="Go back">
            </a>
            
            <input type="submit" value="Apply">
        </div>
    </div>
</form>