<h2 class="alt_header text_align--center">
    So what can you find here?
</h2>

<div class="flex flex_direction--row flex_align_items--stretch gap--32px">
    <a href="/articles" class="card">
        <h3>
            Useful articles
        </h3>
        <h4>
            There is a plenty of useful articles. Just check it out
        </h4>
    </a>
    <a href="/lessons" class="card">
        <h3>
            Lessons in the format of the videos
        </h3>
        <h4>
            Ye have to watch 'em all
        </h4>
    </a>
</div>