<footer class="margin--48px padding--48px border_radius--48px">
    <div>
        <img src="./images/unity-icon-48px.png"/>

        <p class="font_size--body text_align--center">
            Unity is a 3D game engine used for... making 3D games, of course. But not only three-dimensional games can
            be produced. There are tons of capabilities and our goal is to tell you about such capabilities.
        </p>
    </div>

    <div class="flex flex_direction--row">
        <a href="https://www.youtube.com">
            <h6>
                YouTube
            </h6>
        </a>
        <a href="https://www.vk.com">
            <h6>
                VK
            </h6>
        </a>
    </div>
</footer>