<header class="flex flex_direction--row">
    <div class="flex flex_direction--row flex_align_items--center">
        <span id="header__navbutton" class="md_icon icon_size--32px">
            menu
        </span>

        <div id="header__logo">
            <a class="flex flex_direction--row flex_align_items--center" href="/">
                <img src="./images/unity-icon-32px.png">

                <h3>
                    Unity
                </h3>
            </a>
        </div>
    </div>
</header>