<nav class="border_radius--32px">
    <a href="/account">
        <div class="flex flex_direction--row flex_align_items--center gap--16px">
            <span class="md_icon icon_size--24px">
                account_circle
            </span>

            <h5>
                Account
            </h5>
        </div>
    </a>
    <a href="/">
        <div class="flex flex_direction--row flex_align_items--center gap--16px">
            <span class="md_icon icon_size--24px">
                home
            </span>

            <h5>
                Home
            </h5>
        </div>
    </a>

    <h6 class="margin--16px margin--no_horizontal">
        Material
    </h6>

    <a href="/articles">
        <div class="flex flex_direction--row flex_align_items--center gap--16px">
            <span class="md_icon icon_size--24px">
                article
            </span>

            <h5>
                Articles
            </h5>
        </div>
    </a>

    <a href="/videos">
        <div class="flex flex_direction--row flex_align_items--center gap--16px">
            <span class="md_icon icon_size--24px">
                video_library
            </span>

            <h5>
                Videos
            </h5>
        </div>
    </a>
</nav>